### ISSUE TITLE
Add docker wait command

### ISSUE THREAD

**Issue by jaudiger** [getporter/docker-mixin#33]
Reference: https://docs.docker.com/engine/reference/commandline/wait/

Proposed syntax:
```yml
docker-compose:
  description: "Wait a service"
  wait:
    container:
    - containerA
    - container B
``` 

The `wait` command can be useful for synchronization.
