### ISSUE TITLE
Add docker volume command

### ISSUE THREAD

**Issue by jaudiger** [getporter/docker-mixin#35]
Reference: https://docs.docker.com/engine/reference/commandline/volume/

Proposed initial syntax (more can be added in future):

```yml
docker-compose:
  description: "Create a volume"
  volume:
    name: volumeName
``` 

```yml
docker-compose:
  description: "Delete a volume"
  volume:
    name: volumeName
    absent: false
``` 

```yml
docker-compose:
  description: "Force deletion of a volume"
  volume:
    name: volumeName
    absent: false
    force: true
``` 

The `volume` command can be useful to create/delete a volume to share data between containers.
